"$schema" = 'https://starship.rs/config-schema.json'
# https://starship.rs/config/#prompt

add_newline = true

[aws]
force_display = true
style = 'dimmed white'
symbol = '🅰 '

[aws.region_aliases]
ap-east-1 = "ape1"
ap-northeast-1 = "apne1"
ap-northeast-2 = "apne2"
ap-northeast-3 = "apne3"
ap-south-1 = "aps1"
ap-southeast-1 = "apse1"
ap-southeast-2 = "apse2"
ap-southeast-3 = "apse3"
ca-central-1 = "cac1"
eu-central-1 = "euc1"
eu-north-1 = "eun1"
eu-south-1 = "eus1"
eu-west-1 = "euw1"
eu-west-2 = "euw2"
eu-west-3 = "euw3"
af-south-1 = "afs1"
us-gov-east-1 = "usge1"
us-gov-west-1 = "usgw1"
me-central-1 = "mec1"
me-south-1 = "mes1"
cn-north-1 = "cnn1"
cn-northwest-1 = "cnnw1"
sa-east-1 = "sae1"
us-east-1 = "use1"
us-east-2 = "use2"
us-west-1 = "usw1"
us-west-2 = "usw2"

[package]
disabled = true

[time]
disabled = false
format = '[$time]($style) '
time_format = '%H:%M:%S%z'
style = 'bright-white'

[git_branch]
symbol = '⎇ '

[container]
disabled = true

[nodejs]
symbol = 'js:'
version_format = '${raw}'

[terraform]
format = '[$symbol$version]($style) '
symbol = 'TF'
style = 'bright-blue'

#[custom.tf]
#command = 'readlink $(which terraform) | awk -F "_" "NF > 1 {print $NF}"'
#detect_extensions = ['tf', 'tfplan', 'tfstate']

[directory]
format = "[$path]($style)[$read_only]($read_only_style)\n"
truncate_to_repo = false
style= 'yellow'
truncation_length = 8
truncation_symbol = '.../'
